kind: ConfigMap
metadata:
  name: resolver
apiVersion: v1
data:
  iglu_resolver.json: |-
      {
        "schema": "iglu:com.snowplowanalytics.iglu/resolver-config/jsonschema/1-0-1",
        "data": {
          "cacheSize": 500,
          "repositories": [
            {
              "name": "Iglu Central",
              "priority": 0,
              "vendorPrefixes": [ "com.snowplowanalytics" ],
              "connection": {
                "http": {
                  "uri": "http://iglucentral.com"
                }
              }
            },
            {
              "name": "Iglu Central - GCP Mirror",
              "priority": 1,
              "vendorPrefixes": [ "com.snowplowanalytics" ],
              "connection": {
                "http": {
                  "uri": "http://mirror01.iglucentral.com"
                }
              }
            },
            {
              "name": "Your repo name",
              "priority": 3,
              "vendorPrefixes": [ "com.<SOME PREFIX>" ],
              "connection": {
                "http": {
                  "uri": "URI TO YOUR REPO"
                }
              }
            }
          ]
        }
      }
