imports:
  - path: templates/cloudbuild.py
    name: cloudbuild.py


resources:
  - name: snowplow-cloudbuild-auth
    type: cloudbuild.py
    properties:
      steps:
        - name: 'gcr.io/cloud-builders/gcloud'
          args:
          - container
          - clusters
          - get-credentials
          - snowplow-cluster
          - --zone= #TODO: Add desired location, e.g. europe-west1-c

        # Get credentials secret here
        - name: gcr.io/cloud-builders/gcloud
          entrypoint: 'bash'
          args: [ '-c', "gcloud secrets versions access latest --secret=sa_json --format='get(payload.data)' | tr '_-' '/+' | base64 -d > credentials-secret.yaml" ]
        - name: "gcr.io/cloud-builders/gke-deploy"
          args:
            - run
            - --filename=credentials-secret.yaml
            - --location= #TODO: Add desired location, e.g. europe-west1-c
            - --cluster=snowplow-cluster
 
  # Deploy bq
  - name: snowplow-cloudbuild-deploy-bq-loader
    type: cloudbuild.py
    properties:
      steps:
        - name: 'gcr.io/cloud-builders/gcloud'
          args:
          - source
          - repos
          - clone
          -  #TODO: ADD GITHUB PROJECT
          - --project= #TODO: Add project id

        # Deploy bq loader
        - name: "gcr.io/cloud-builders/gke-deploy"
          args:
          - run
          - --filename= #TODO: ADD GITHUB PROJECT/iac-setup/k8s/bq/bq-loader-dm.yaml
          - --location= #TODO: Add desired location, e.g. europe-west1-c
          - --cluster=snowplow-cluster

  - name: snowplow-cloudbuild-deploy-bq-mutator-listener
    type: cloudbuild.py
    properties:
      steps:
        - name: 'gcr.io/cloud-builders/gcloud'
          args:
          - source
          - repos
          - clone
          -  #TODO: ADD GITHUB PROJECT
          - --project= #TODO: Add project id

        # Deploy bq mutator
        - name: "gcr.io/cloud-builders/gke-deploy"
          args:
          - run
          - --filename= #TODO: ADD GITHUB PROJECT/iac-setup/k8s/bq/bq-mutator-listener-dm.yaml
          - --location= #TODO: Add desired location, e.g. europe-west1-c
          - --cluster=snowplow-cluster